#!/usr/bin/env python3
"""
build-standalone.py — Bundle index.html + js/*.js into a single self-contained HTML.

The output file has no external dependencies (except CDN Tailwind for the wizard
shell, which the exported customer profile does NOT depend on — the exported
profile ships its own inlined CSS).

Usage:
    python3 build-standalone.py                   # writes Unified_Profile_Generator.html
    python3 build-standalone.py -o custom.html    # writes to custom.html
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX = ROOT / "index.html"

# Script tags in load order — mirrors index.html
SCRIPTS = [
    "js/defaults.js",
    "js/images.js",
    "js/generator.js",
    "js/pagehost.js",
    "js/localai.js",
    "js/app.js",
]


def build(out_path: Path) -> None:
    if not INDEX.exists():
        sys.exit(f"error: {INDEX} not found")

    html = INDEX.read_text(encoding="utf-8")

    # Strip the dev-time dynamic script loader (an inline <script> that
    # createElement()s each module URL with a cache-busting query param).
    # We match everything from the __UPG_BUILD__ marker to the end of the
    # following </script> block (the actual loader).
    html = re.sub(
        r'\s*<script>window\.__UPG_BUILD__.*?</script>\s*'
        r'<script>[\s\S]*?document\.body\.appendChild\(s\);[\s\S]*?</script>',
        "",
        html,
        flags=re.MULTILINE,
    )
    # Also strip the older static <script src="js/..."> form if present.
    html = re.sub(
        r'\s*<script src="js/[^"]+"></script>\n?', "", html, flags=re.MULTILINE
    )

    # Build one big inlined <script> block
    inlined = ["<script>"]
    for rel in SCRIPTS:
        p = ROOT / rel
        if not p.exists():
            sys.exit(f"error: missing script {p}")
        inlined.append(f"// ==== inlined from ./{rel} ====")
        inlined.append(p.read_text(encoding="utf-8"))
        inlined.append("")
    inlined.append("</script>")
    inlined_block = "\n".join(inlined)

    # Insert before </body>
    html = html.replace("</body>", inlined_block + "\n</body>")

    # Add a banner comment at the top
    banner = (
        "<!--\n"
        "  Unified_Profile_Generator.html — auto-generated by build-standalone.py.\n"
        "  Do not edit directly; edit index.html + js/*.js and rerun the bundler.\n"
        "-->\n"
    )
    if html.startswith("<!DOCTYPE html>"):
        html = "<!DOCTYPE html>\n" + banner + html[len("<!DOCTYPE html>\n"):]
    else:
        html = banner + html

    out_path.write_text(html, encoding="utf-8")
    size_kb = out_path.stat().st_size / 1024
    print(f"✓ wrote {out_path.name} ({size_kb:.1f} KB)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default="Unified_Profile_Generator.html")
    args = ap.parse_args()
    out = ROOT / args.out
    build(out)


if __name__ == "__main__":
    main()
